services:
  spark:
    image: spark-dev
    container_name: spark-dev
    ports:
      - "2222:22"
    environment:
      - JAVA_HOME=/opt/java/openjdk
      - SPARK_HOME=/opt/spark
    volumes:
      - ./:/app
      - ./data:/data
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: "24g"
        reservations:
          cpus: "8.0"
          memory: "16g"

  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db:/var/lib/postgresql/data

