services:
  spark:
    image: spark-dev
    container_name: spark-dev
    ports:
      - "2222:22"
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: "24g"
        reservations:
          cpus: "8.0"
          memory: "16g"
