services:
  spark:
    image: andyandyandyandy2023/spark-dev:latest
    container_name: spark-dev
    ports:
      - "2222:22"
    volumes:
      - app:/app
    networks:
      - spark-network
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: "24g"
        reservations:
          cpus: "8.0"
          memory: "16g"

  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spark-network
    command: postgres -c max_connections=300

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    networks:
      - spark-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin

networks:
  spark-network:
    driver: bridge

volumes:
  postgres_data:
  app: 