[project]
name = "spark-dev"
version = "0.1.0"
description = "My Spark development environment"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyspark>=3.5.4",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.6",
]
